[docs] Add getting started page with project templates
eclipsesource/graphical-lsp-website pull request #53
Opened 2022-04-28 14:26 UTC by planger

Also restructures documentation in general to allow adopters proceeding more quickly to the getting started page.
Adds a place holder for model operations, which we will add soon.

Contributed on behalf of STMicroelectronics.

2022-04-28 23:24 UTC, tortmayr requested changes
Thanks you Philip for this huge documentation improvement! I really like the 
restructuring and the new getting started section. This is a huge step forward in lowering the entry  barrier for people interested in GLSP .

I did an extensive review of all you changes and also quickly parsed the unchanged sections to see if we missed something there. In addition, I have double checked wether all links work as expected.

You can find my suggestions and comments in-line. 

In addition, to this in-line suggestions I noticed the following three issues:

### The `one-sentence-per-line` pattern for markdown files is not used consistently. 
While are following the pattern in most sections there are some cases where multiple sentences are part of one line. 

I think we should double check this and ensure that we use one line per sentence. This procuded much nicer git diffs. 

If have added comments regarding this to  the root index [content.md](https://github.com/eclipsesource/graphical-lsp-website/pull/53/files#diff-4c8a825efe112f54d69c1c18270485e34098649f15c66ce808406523cfc88a05) file but did not do it for other files to avoid `inline-comment pollution` :wink: 

### The node snippets regarding di configuration are outdated.
With https://github.com/eclipse-glsp/glsp-server-node/pull/15 the di configuration approach got changed. As a consequence many node snippets are now outdated and need to be updated

### In the `Actions & Action handler` overview the node snippets are not collapsed by default

Overall this is an amazing change! Great work!

2022-04-28 23:24 UTC, tortmayr commented on content/documentation/actionhandler/content.md
Intended for line 81:
> Each action specification has a unique “kind” and can optionally declare additional data properties We recommend

Missing dot:  ... declare additional data properties. We recommend ...

2022-04-29 08:02 UTC, planger commented on content/documentation/integrations/content.md
> +* If you want to work with EMF source models directly from your GLSP server, e.g. because you want to benefit from its command stack implementation, change notification support, etc. and don't want o
I removed this part of the sentence.

2022-04-29 08:07 UTC, planger commented on content/documentation/overview/content.md
> +Each diagram editor is considered to be a single *GLSP client*.
Thanks, I tried to clarify.

2022-04-29 10:10 UTC, tortmayr commented on content/documentation/actionhandler/content.md
This still seems to be unresolved, unless I missed it.

2022-04-29 10:11 UTC, tortmayr approved these changes

2022-04-29 10:12 UTC, tortmayr commented
I guess the issue regarding the `one-sentence-per-line` convention is also unresolved, but I'm also fine with not doing that now

2022-04-29 10:31 UTC, planger commented
> Thank you Philip. The changes look good to me. There is one comment that still seems to be unresolved: [#53 (comment)](https://github.com/eclipsesource/graphical-lsp-website/pull/53#discussion_r861372499).

Right, fixed.

> I guess the issue regarding the one-sentence-per-line convention is also unresolved, but I'm also fine with not doing that now

Yeah, I omitted that for now in the existing text. The new text that I added should largely respect that it.

2022-04-29 10:32 UTC, merged