Enhance documentation on layouting GLSP diagrams
eclipsesource/graphical-lsp-website pull request #56
Opened 2022-05-18 11:38 UTC by ndoschek

- Add markdownlint and cspell as recommended extensions
  - Add settings for markdownlint and prettier support for markdown and json files
- Add documentation for UI extensions
  - Add separate page for UI extensions
  - Documentation and implementation showcase
- Add documentation for Layouters
- Add documentation for default views

Contributed on behalf of STMicroelectronics.

2022-05-18 13:32 UTC, planger requested changes
Thank you very much Nina! This adds urgently needed documentation and for sure will help newcomers to get started, but even more experienced developers to add more UI controls, etc.

Please find a few comments inline!

2022-05-18 13:32 UTC, planger commented on content/documentation/clientLayouting/content.md
> +which increases all children sizes by this value in both width and height, the default value is `50px`.
```suggestion
which increases the widths and heights of all children by a specified value, the default value is `50` pixel.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/clientLayouting/content.md
> +For independent implementations that extend the `AbstractLayout`, it will be bound as follows:
```suggestion
Custom layouter, which don't overwrite existing ones should extend the `AbstractLayout` and can be registered for a certain layouter key, e.g. `MyCustomLayouter.KIND`, that is used in the `layout` property of compartments as follows:
```

2022-05-18 13:32 UTC, planger commented on content/documentation/clientLayouting/content.md
> +Then the custom layouter is ready to use:
```suggestion
With that, the custom layouter is ready to be used by compartments in the graphical model:
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The computation of the radius can be overriden and adapted to custom needs.
Do you mean with "overriden" that it can be overriden by specifying the value in the GModelElement? I think this should be specified more clearly.

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The `ExpandButtonView` renders a SVG element in the shape of a triangle that allows exapandable parent elements to trigger expansion, for example to display further element information.
```suggestion
The `ExpandButtonView` renders a SVG element in the shape of a triangle that allows expandable parent elements to trigger expansion, for example to display further element information.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The `PreRenderedView` visualizes a previously rendered piece of svg code as a separate SVG element.
```suggestion
The `PreRenderedView` visualizes a previously rendered piece of svg code as a separate SVG element.
This enables putting SVG code directly in the graphical model, which may be useful for including complex images for certain use cases.
However, usually it is recommended to create a dedicated element type and register a dedicated view, which produces custom SVG, as this yields more flexibility to take bounds, etc., into account.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +A `RectangularNodeView` creates a rectangular shape based shape's size.
```suggestion
A `RectangularNodeView` creates a rectangular shape based on the shape's size.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The `SGraphView` renders the base svg canvas for an SModel and triggers the rendering of its children.
```suggestion
The `SGraphView` renders the base SVG canvas for an SModel and triggers the rendering of its children.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +Its position is computed by either a register `EdgeRouterRegistry` or passed routing arguments.
```suggestion
Its position is computed either by a registered `EdgeRouterRegistry` or the routing arguments of the element.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +configureModelElement(
I'm not sure how useful the registration code is. I think it'd be more useful (but also more work), to show an example of creating such a node in the GModelFactory and show a screenshot of the result.

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +A `GIssueMarkerView` renders a issue marker on top of shapes that have a validation issue.
```suggestion
A `GIssueMarkerView` renders an issue marker on top of shapes. This is used to show validation results on elements (see Model Validation).
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +A `RectangularNodeView` creates a rectangular shape based shape's size and computes and renders the corners in a rounded way, based on the given options (i.e. `getClipPathInsets`).
I think the corner radius defaults to 0, so it is worth mentioning that the corner radius needs to be specified.
Also I'd mention all arguments and how they need to be passed.

This is related to the comment above that an example of creating a GModelElement that uses this type might be more helpful than showing the registration.

Also a link to the source code might be very helpful in general for all the views mentioned here.

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +
What is that?

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The `ForeignObjectView` renders a box , which is usually contained by a default node view, which takes care of resizing and moving of the element.
```suggestion
The `ForeignObjectView` renders elements that are foreign to SVG, such as HTML, MathML, etc. as specified in their `namespace` and `code` property. Usually such an element is contained by a node view that enables features, such as resizing and moving of the element.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +The view then renders the provided code snippet, e.g. a `<pre>` element.
```suggestion
```

2022-05-18 13:32 UTC, planger commented on content/documentation/rendering/content.md
> +An example use case for using a `ForeignObjectView` is for example a multiline-text-box.
```suggestion
A common example use case for using a `ForeignObjectView` is to benefit from word wrapping support of HTML to show multiline text box.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +An UI Extension is a concept provided by the underlying framework Sprotty, which allows to display additional UI HTML elements on topf of a diagram.
```suggestion
A UI Extension is a concept provided by the underlying framework Sprotty, which allows to display additional UI HTML elements on top of a diagram.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +It is often used to add UI controls to the diagram, good base examples are:
```suggestion
It is often used to add UI controls to the diagram. It is also frequently used in the core GLSP functionality:
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +To add custom UI elements, the abstract methods `initializeContents` shall be implemented.
```suggestion
To add the actual UI elements to the DOM, the abstract method `initializeContents` must be implemented.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +To enable an UI Extension the corresponding Action or Command shall be used, namely [`SetUIExtensionVisibilityAction`][uiex-registry] or [`SetUIExtensionVisibilityCommand`][uiex-registry].
```suggestion
To enable a UI Extension a [`SetUIExtensionVisibilityAction`][uiex-registry] or [`SetUIExtensionVisibilityCommand`][uiex-registry] with the respective UI Extension ID needs to be invoked.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +UI extensions can be enabled via context menu entries, mouse click events, keyboard events or changes of the diagram itself, for example the change of the diagram's `EditMode`.
```suggestion
UI extensions can be enabled practically with any event that can dispatch an action, e.g. via context menu entries, mouse click events, keyboard events or changes of the diagram itself, for example the change of the diagram's `EditMode`.
```

2022-05-18 13:32 UTC, planger commented on content/documentation/ui-extensions/content.md
> +Activate ui extension, for example directly after all necessary initially Actions where dispatched in [GLSPDiagramWidget#`dispatchInitialActions()`](https://github.com/eclipse-glsp/glsp-theia-integra
```suggestion
To activate our UI extension, for example, alongside the initial actions, we can dispatch the `SetUIExtensionVisibilityAction` in [GLSPDiagramWidget#`dispatchInitialActions()`](https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts) after a certain delay.
```

2022-05-19 15:42 UTC, ndoschek commented
Hi @planger, I uploaded a first update that addresses your review comments.
Regarding teh default view descriptions, I will add a second commit for that (and I also left those comments unresolved for now).

2022-05-19 16:30 UTC, planger reviewed
Wow that's awesome! Thank you very much! Great work!

2022-05-19 16:30 UTC, planger commented
Do you want to merge the current version already and open a second PR or are you planning to append a commit to this PR?
I'm fine with either way!

2022-05-20 07:53 UTC, ndoschek commented
Thanks a lot @planger! I added the proper search site (when clicking on the search icon in the search fragment in the navigation bar) and fixed some minor typos and markdownlint issues.
Sounds good for merging that state, I will continue on integrating the remaining comments about the default views in a separate PR then. Thanks again!

2022-05-20 08:13 UTC, planger approved these changes
Thank you very much, Nina! Excellent work so far!

2022-05-20 08:13 UTC, merged

2022-05-20 16:28 UTC, ndoschek commented on content/documentation/rendering/content.md
> +The computation of the radius can be overriden and adapted to custom needs.
Adressed in PR #57

2022-05-20 16:28 UTC, ndoschek commented on content/documentation/rendering/content.md
> +configureModelElement(
Adressed in PR https://github.com/eclipsesource/graphical-lsp-website/pull/57

2022-05-20 16:29 UTC, ndoschek commented on content/documentation/rendering/content.md
> +A `RectangularNodeView` creates a rectangular shape based shape's size and computes and renders the corners in a rounded way, based on the given options (i.e. `getClipPathInsets`).
Thanks, yes I totally agree, I addressed this in PR https://github.com/eclipsesource/graphical-lsp-website/pull/57

2022-05-20 16:29 UTC, ndoschek commented on content/documentation/rendering/content.md
> +
Oh sorry, I oversaw that section, I addressed this in PR https://github.com/eclipsesource/graphical-lsp-website/pull/57